apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: cloudopsk8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: registry
          image: registry:latest  # Use the Docker registry image from Docker Hub
          ports:
            - containerPort: 5000  # Port to access the registry
          volumeMounts:
            - name: registry-storage
              mountPath: /var/lib/registry
          env:
            - name: REGISTRY_AUTH
              value: htpasswd
            - name: REGISTRY_AUTH_HTPASSWD_REALM
              value: Registry Realm
            - name: REGISTRY_AUTH_HTPASSWD_PATH
              value: /auth/htpasswd
          resources:
            limits:
              memory: "128Mi"  # Adjust resource limits as needed
              cpu: "100m"
      volumes:
        - name: registry-storage
          emptyDir: {}
        - name: auth-volume
          secret:
            secretName: registry-secret
