apiVersion: v1
kind: Service
metadata:
  name: docker-registry-service
  namespace: cloudopsk8
spec:
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5000  # Port to access the registry within the cluster
