apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
  namespace: default
data:
  config.yml: |
    registry:
      server: registry.example.com
      port: 5000
    logging:
      level: info
   
