apiVersion: v1
kind: Secret
metadata:
  name: registry-secret
  namespace: default
type: docker-registry
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSI0NDk2Njk5NjgxNjkuZGtyLmVjci51cy1lYXN0LTEuYW1hem9uYXdzLmNvbSI6IHt9LAoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7fQoJfSwKCSJjcmVkc1N0b3JlIjogImRlc2t0b3AiLAoJInBsdWdpbnMiOiB7CgkJIi14LWNsaS1oaW50cyI6IHsKCQkJImVuYWJsZWQiOiAidHJ1ZSIKCQl9Cgl9Cn0=
